{"name": "Unstable test", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 2\n +  where 1 = <bound method Random.randint of <random.Random object at 0x1258b9a10>>(1, 2)\n +    where <bound method Random.randint of <random.Random object at 0x1258b9a10>> = random.randint", "trace": "self = <testproject.tests.ui.test_pytest_markers.TestLogin object at 0x10463fe50>\n\n    @allure.title(\"Unstable test\")\n    @pytest.mark.flaky(max_runs=3, rerun_filter=lambda: time.sleep(1))\n    def test_unstable(self):\n>       assert random.randint(1, 2) == 2\nE       assert 1 == 2\nE        +  where 1 = <bound method Random.randint of <random.Random object at 0x1258b9a10>>(1, 2)\nE        +    where <bound method Random.randint of <random.Random object at 0x1258b9a10>> = random.randint\n\ntests/ui/test_pytest_markers.py:41: AssertionError"}, "attachments": [{"name": "stdout", "source": "d63a7ae8-ae67-420e-9460-18401feb41af-attachment.txt", "type": "text/plain"}], "start": 1660750784930, "stop": 1660750784930, "uuid": "5fc23e82-1da4-4396-98ff-8af12475741c", "historyId": "2d26c4eea3237e802dcb5cbe6e2e587b", "testCaseId": "0b4e007e72c2a6d01c19bce6a0f3d1bc", "fullName": "tests.ui.test_pytest_markers.TestLogin#test_unstable", "labels": [{"name": "tag", "value": "flaky(max_runs=3, rerun_filter=<function TestLogin.<lambda> at 0x10465c550>)"}, {"name": "parentSuite", "value": "tests.ui"}, {"name": "suite", "value": "test_pytest_markers"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "Admin-Air.local"}, {"name": "thread", "value": "28094-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.ui.test_pytest_markers"}]}